<?php
/**
 * Created by PhpStorm.
 * User: Stas
 * Date: 02/05/19
 * Time: 12:02
 */

require_once "Middleware.php";
require_once __DIR__ . "/../../core/utility/util_functions.php";

class AdminRightsMiddleware extends Middleware
{

    public function handle()
    {
        session_start();
        $cur_role = $_SESSION['user-role'];

        if ($cur_role == "ADMIN"){
            return true;
        }
        return false;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }



}
