<?php
/**
 * Created by PhpStorm.
 * User: Stas
 * Date: 02/05/19
 * Time: 12:02
 */

require_once "Middleware.php";
require_once __DIR__ . "/../../core/utility/util_functions.php";

class AuthMiddleware extends Middleware
{
    public function handle()
    {
        session_start();

        if ($this->isSetUser($_POST['email'], $_POST['password'])) {
            return true;
        } else {
            return false;
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }


    function getAllUser()
    {
        $usersOrm = new User("students");
        $users = $usersOrm->select()->get();
        return $users;
    }

    function isSetUser($email, $password)
    {
        $allUsers = $this->getAllUser();

        if (!empty($allUsers)) {
            foreach ($allUsers as $user) {

                if ($email == $user->email and $password == $user->password) {
                    $_SESSION['user'] = $user;
                    $role = User::getRoleValueById($user->id_role);
                    $_SESSION['user-role'] = $role;
                    return true;
                }
            }
        }
        return false;
    }
}


//
//$users = AuthMiddleware::getAllUser();
//
//print_r($users);
//









//<?php
///**
// * Created by PhpStorm.
// * User: Stas
// * Date: 02/05/19
// * Time: 12:02
// */
//
//require_once "Middleware.php";
//
//class AuthMiddleware extends Middleware
//{
//    public function handle()
//    {
//        session_start();
//
//        if ($this->isSetUser($_POST['login'], $_POST['password'])) {
//
//            setcookie("city", $_POST['city'], time()+36000);
//            setcookie("language", $_POST['language'],time()+36000);
//
//            echo "<script>alert('login successful');</script>";
//
//            return true;
//        } else {
//            echo "<script>alert('User not found');</script>";
//            return false;
//        }
//    }
//
//    public function run()
//    {
//        parent::run(); // TODO: Change the autogenerated stub
//    }
//
//
//
//
//
//
//
//
//    function getAllUser()
//    {
//        //$myDBpath = "usersDB.txt";
//        $myDBpath = __DIR__ . "\..\..\core\db\usersDB.txt";
//        $users = [];
//        if (file_exists($myDBpath)) {
//            $t = file_get_contents($myDBpath);
////        var_dump($t);
////        echo "<br>";
//            $t2 = explode(';', $t);
//            foreach ($t2 as $userString) {
//                $users[] = explode(':', $userString);
//            }
//        }
////    var_dump($users);
////    echo "<br>";
//        return $users;
//    }
//
//    function isSetUser($login, $password)
//    {
//        $allUsers = $this->getAllUser();
////
////        echo "all:LLL:";
////        debug($allUsers);
//
//        if ( ! empty($allUsers)) {
//            foreach ($allUsers as $user) {
//                if ($login == $user[0] and $password == $user[1]) {
//                    $_SESSION['user'] = $user[0];
//                    return true;
//                }
//            }
//        }
//    }
//}