<?php
/**
 * Created by PhpStorm.
 * User: Stas
 * Date: 02/05/19
 * Time: 12:02
 */

require_once "Middleware.php";
require_once __DIR__ . "/../../core/utility/util_functions.php";

class AuthMiddleware extends Middleware
{
    public function handle()
    {
        session_start();

        if ($this->isSetUser($_POST['email'], $_POST['password'])) {
            return true;
        } else {
            return false;
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }


    function getAllUser()
    {
        $usersOrm = new User("students");
        $users = $usersOrm->select()->get();
        return $users;
    }

    function isSetUser($email, $password)
    {
        $allUsers = $this->getAllUser();

        if (!empty($allUsers)) {
            foreach ($allUsers as $user) {

                if ($email == $user->email and $password == $user->password) {
                    $_SESSION['user'] = $user;
                    $role = User::getRoleValueById($user->id_role);
                    $_SESSION['user-role'] = $role;
                    return true;
                }
            }
        }
        return false;
    }
}

