<?php
/**
 * Created by PhpStorm.
 * User: Stas
 * Date: 02/05/19
 * Time: 12:02
 */

require_once "Middleware.php";

class LocaleMiddleware extends Middleware
{
    public function handle()
    {
        session_start();
        if (isset($_GET['lang'])) {
            $_SESSION['lang'] = $_GET['lang'];
        }
        return isset($_SESSION['lang']) ? $_SESSION['lang'] : "ua";
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }

}



