<?php
/**
 * Created by PhpStorm.
 * User: Stas
 * Date: 02/05/19
 * Time: 12:02
 */

require_once "Middleware.php";
require_once __DIR__ . "/../../core/utility/util_functions.php";

class StudentRightsMiddleware extends Middleware
{

    public function handle()
    {
        session_start();
        $cur_role = $_SESSION['user-role'];

        if ($cur_role == "STUDENT"){
            return true;
        }
        return false;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }



}


//
//$users = AuthMiddleware::getAllUser();
//
//print_r($users);
//









//<?php
///**
// * Created by PhpStorm.
// * User: Stas
// * Date: 02/05/19
// * Time: 12:02
// */
//
//require_once "Middleware.php";
//
//class AuthMiddleware extends Middleware
//{
//    public function handle()
//    {
//        session_start();
//
//        if ($this->isSetUser($_POST['login'], $_POST['password'])) {
//
//            setcookie("city", $_POST['city'], time()+36000);
//            setcookie("language", $_POST['language'],time()+36000);
//
//            echo "<script>alert('login successful');</script>";
//
//            return true;
//        } else {
//            echo "<script>alert('User not found');</script>";
//            return false;
//        }
//    }
//
//    public function run()
//    {
//        parent::run(); // TODO: Change the autogenerated stub
//    }
//
//
//
//
//
//
//
//
//    function getAllUser()
//    {
//        //$myDBpath = "usersDB.txt";
//        $myDBpath = __DIR__ . "\..\..\core\db\usersDB.txt";
//        $users = [];
//        if (file_exists($myDBpath)) {
//            $t = file_get_contents($myDBpath);
////        var_dump($t);
////        echo "<br>";
//            $t2 = explode(';', $t);
//            foreach ($t2 as $userString) {
//                $users[] = explode(':', $userString);
//            }
//        }
////    var_dump($users);
////    echo "<br>";
//        return $users;
//    }
//
//    function isSetUser($login, $password)
//    {
//        $allUsers = $this->getAllUser();
////
////        echo "all:LLL:";
////        debug($allUsers);
//
//        if ( ! empty($allUsers)) {
//            foreach ($allUsers as $user) {
//                if ($login == $user[0] and $password == $user[1]) {
//                    $_SESSION['user'] = $user[0];
//                    return true;
//                }
//            }
//        }
//    }
//}